/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.entity.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.entity.jooq.tables.AppPermissionGroup;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppPermissionGroupRecord extends UpdatableRecordImpl<AppPermissionGroupRecord> implements Record2<ULong, ULong> {

    private static final long serialVersionUID = -237508366;

    /**
     * Setter for <code>oagi.app_permission_group.app_permission_id</code>.
     */
    public void setAppPermissionId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.app_permission_group.app_permission_id</code>.
     */
    public ULong getAppPermissionId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.app_permission_group.app_group_id</code>.
     */
    public void setAppGroupId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.app_permission_group.app_group_id</code>.
     */
    public ULong getAppGroupId() {
        return (ULong) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<ULong, ULong> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<ULong, ULong> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return AppPermissionGroup.APP_PERMISSION_GROUP.APP_PERMISSION_ID;
    }

    @Override
    public Field<ULong> field2() {
        return AppPermissionGroup.APP_PERMISSION_GROUP.APP_GROUP_ID;
    }

    @Override
    public ULong component1() {
        return getAppPermissionId();
    }

    @Override
    public ULong component2() {
        return getAppGroupId();
    }

    @Override
    public ULong value1() {
        return getAppPermissionId();
    }

    @Override
    public ULong value2() {
        return getAppGroupId();
    }

    @Override
    public AppPermissionGroupRecord value1(ULong value) {
        setAppPermissionId(value);
        return this;
    }

    @Override
    public AppPermissionGroupRecord value2(ULong value) {
        setAppGroupId(value);
        return this;
    }

    @Override
    public AppPermissionGroupRecord values(ULong value1, ULong value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppPermissionGroupRecord
     */
    public AppPermissionGroupRecord() {
        super(AppPermissionGroup.APP_PERMISSION_GROUP);
    }

    /**
     * Create a detached, initialised AppPermissionGroupRecord
     */
    public AppPermissionGroupRecord(ULong appPermissionId, ULong appGroupId) {
        super(AppPermissionGroup.APP_PERMISSION_GROUP);

        set(0, appPermissionId);
        set(1, appGroupId);
    }
}
