/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.entity.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.entity.jooq.enums.SeqKeyType;
import org.oagi.score.entity.jooq.tables.SeqKey;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeqKeyRecord extends UpdatableRecordImpl<SeqKeyRecord> implements Record6<ULong, ULong, SeqKeyType, ULong, ULong, ULong> {

    private static final long serialVersionUID = -364609995;

    /**
     * Setter for <code>oagi.seq_key.seq_key_id</code>.
     */
    public void setSeqKeyId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.seq_key.seq_key_id</code>.
     */
    public ULong getSeqKeyId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.seq_key.from_acc_id</code>.
     */
    public void setFromAccId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.seq_key.from_acc_id</code>.
     */
    public ULong getFromAccId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.seq_key.type</code>.
     */
    public void setType(SeqKeyType value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.seq_key.type</code>.
     */
    public SeqKeyType getType() {
        return (SeqKeyType) get(2);
    }

    /**
     * Setter for <code>oagi.seq_key.cc_id</code>.
     */
    public void setCcId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.seq_key.cc_id</code>.
     */
    public ULong getCcId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.seq_key.prev_seq_key_id</code>.
     */
    public void setPrevSeqKeyId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.seq_key.prev_seq_key_id</code>.
     */
    public ULong getPrevSeqKeyId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>oagi.seq_key.next_seq_key_id</code>.
     */
    public void setNextSeqKeyId(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.seq_key.next_seq_key_id</code>.
     */
    public ULong getNextSeqKeyId() {
        return (ULong) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<ULong, ULong, SeqKeyType, ULong, ULong, ULong> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<ULong, ULong, SeqKeyType, ULong, ULong, ULong> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return SeqKey.SEQ_KEY.SEQ_KEY_ID;
    }

    @Override
    public Field<ULong> field2() {
        return SeqKey.SEQ_KEY.FROM_ACC_ID;
    }

    @Override
    public Field<SeqKeyType> field3() {
        return SeqKey.SEQ_KEY.TYPE;
    }

    @Override
    public Field<ULong> field4() {
        return SeqKey.SEQ_KEY.CC_ID;
    }

    @Override
    public Field<ULong> field5() {
        return SeqKey.SEQ_KEY.PREV_SEQ_KEY_ID;
    }

    @Override
    public Field<ULong> field6() {
        return SeqKey.SEQ_KEY.NEXT_SEQ_KEY_ID;
    }

    @Override
    public ULong component1() {
        return getSeqKeyId();
    }

    @Override
    public ULong component2() {
        return getFromAccId();
    }

    @Override
    public SeqKeyType component3() {
        return getType();
    }

    @Override
    public ULong component4() {
        return getCcId();
    }

    @Override
    public ULong component5() {
        return getPrevSeqKeyId();
    }

    @Override
    public ULong component6() {
        return getNextSeqKeyId();
    }

    @Override
    public ULong value1() {
        return getSeqKeyId();
    }

    @Override
    public ULong value2() {
        return getFromAccId();
    }

    @Override
    public SeqKeyType value3() {
        return getType();
    }

    @Override
    public ULong value4() {
        return getCcId();
    }

    @Override
    public ULong value5() {
        return getPrevSeqKeyId();
    }

    @Override
    public ULong value6() {
        return getNextSeqKeyId();
    }

    @Override
    public SeqKeyRecord value1(ULong value) {
        setSeqKeyId(value);
        return this;
    }

    @Override
    public SeqKeyRecord value2(ULong value) {
        setFromAccId(value);
        return this;
    }

    @Override
    public SeqKeyRecord value3(SeqKeyType value) {
        setType(value);
        return this;
    }

    @Override
    public SeqKeyRecord value4(ULong value) {
        setCcId(value);
        return this;
    }

    @Override
    public SeqKeyRecord value5(ULong value) {
        setPrevSeqKeyId(value);
        return this;
    }

    @Override
    public SeqKeyRecord value6(ULong value) {
        setNextSeqKeyId(value);
        return this;
    }

    @Override
    public SeqKeyRecord values(ULong value1, ULong value2, SeqKeyType value3, ULong value4, ULong value5, ULong value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeqKeyRecord
     */
    public SeqKeyRecord() {
        super(SeqKey.SEQ_KEY);
    }

    /**
     * Create a detached, initialised SeqKeyRecord
     */
    public SeqKeyRecord(ULong seqKeyId, ULong fromAccId, SeqKeyType type, ULong ccId, ULong prevSeqKeyId, ULong nextSeqKeyId) {
        super(SeqKey.SEQ_KEY);

        set(0, seqKeyId);
        set(1, fromAccId);
        set(2, type);
        set(3, ccId);
        set(4, prevSeqKeyId);
        set(5, nextSeqKeyId);
    }
}
