/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.score.repo.api.impl.jooq.entity.Indexes;
import org.oagi.score.repo.api.impl.jooq.entity.Keys;
import org.oagi.score.repo.api.impl.jooq.entity.Oagi;
import org.oagi.score.repo.api.impl.jooq.entity.tables.records.AppPermissionGroupRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppPermissionGroup extends TableImpl<AppPermissionGroupRecord> {

    private static final long serialVersionUID = 922386971;

    /**
     * The reference instance of <code>oagi.app_permission_group</code>
     */
    public static final AppPermissionGroup APP_PERMISSION_GROUP = new AppPermissionGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppPermissionGroupRecord> getRecordType() {
        return AppPermissionGroupRecord.class;
    }

    /**
     * The column <code>oagi.app_permission_group.app_permission_id</code>.
     */
    public final TableField<AppPermissionGroupRecord, ULong> APP_PERMISSION_ID = createField(DSL.name("app_permission_id"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>oagi.app_permission_group.app_group_id</code>.
     */
    public final TableField<AppPermissionGroupRecord, ULong> APP_GROUP_ID = createField(DSL.name("app_group_id"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>oagi.app_permission_group</code> table reference
     */
    public AppPermissionGroup() {
        this(DSL.name("app_permission_group"), null);
    }

    /**
     * Create an aliased <code>oagi.app_permission_group</code> table reference
     */
    public AppPermissionGroup(String alias) {
        this(DSL.name(alias), APP_PERMISSION_GROUP);
    }

    /**
     * Create an aliased <code>oagi.app_permission_group</code> table reference
     */
    public AppPermissionGroup(Name alias) {
        this(alias, APP_PERMISSION_GROUP);
    }

    private AppPermissionGroup(Name alias, Table<AppPermissionGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppPermissionGroup(Name alias, Table<AppPermissionGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> AppPermissionGroup(Table<O> child, ForeignKey<O, AppPermissionGroupRecord> key) {
        super(child, key, APP_PERMISSION_GROUP);
    }

    @Override
    public Schema getSchema() {
        return Oagi.OAGI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.APP_PERMISSION_GROUP_APP_PERMISSION_ID);
    }

    @Override
    public UniqueKey<AppPermissionGroupRecord> getPrimaryKey() {
        return Keys.KEY_APP_PERMISSION_GROUP_PRIMARY;
    }

    @Override
    public List<UniqueKey<AppPermissionGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<AppPermissionGroupRecord>>asList(Keys.KEY_APP_PERMISSION_GROUP_PRIMARY);
    }

    @Override
    public List<ForeignKey<AppPermissionGroupRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AppPermissionGroupRecord, ?>>asList(Keys.APP_PERMISSION_GROUP_FK_2, Keys.APP_PERMISSION_GROUP_FK_1);
    }

    public AppPermission appPermission() {
        return new AppPermission(this, Keys.APP_PERMISSION_GROUP_FK_2);
    }

    public AppGroup appGroup() {
        return new AppGroup(this, Keys.APP_PERMISSION_GROUP_FK_1);
    }

    @Override
    public AppPermissionGroup as(String alias) {
        return new AppPermissionGroup(DSL.name(alias), this);
    }

    @Override
    public AppPermissionGroup as(Name alias) {
        return new AppPermissionGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppPermissionGroup rename(String name) {
        return new AppPermissionGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppPermissionGroup rename(Name name) {
        return new AppPermissionGroup(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<ULong, ULong> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
