/*
 * This file is generated by jOOQ.
 */
package org.oagi.srt.entity.jooq.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.srt.entity.jooq.Keys;
import org.oagi.srt.entity.jooq.Oagi;
import org.oagi.srt.entity.jooq.tables.records.AppOauth2UserRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppOauth2User extends TableImpl<AppOauth2UserRecord> {

    private static final long serialVersionUID = 790291370;

    /**
     * The reference instance of <code>oagi.app_oauth2_user</code>
     */
    public static final AppOauth2User APP_OAUTH2_USER = new AppOauth2User();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppOauth2UserRecord> getRecordType() {
        return AppOauth2UserRecord.class;
    }

    /**
     * The column <code>oagi.app_oauth2_user.app_oauth2_user_id</code>. Primary key.
     */
    public final TableField<AppOauth2UserRecord, ULong> APP_OAUTH2_USER_ID = createField(DSL.name("app_oauth2_user_id"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Primary key.");

    /**
     * The column <code>oagi.app_oauth2_user.app_user_id</code>. A reference to the record in `app_user`. If it is not set, this is treated as a pending record.
     */
    public final TableField<AppOauth2UserRecord, ULong> APP_USER_ID = createField(DSL.name("app_user_id"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "A reference to the record in `app_user`. If it is not set, this is treated as a pending record.");

    /**
     * The column <code>oagi.app_oauth2_user.oauth2_app_id</code>. A reference to the record in `oauth2_app`.
     */
    public final TableField<AppOauth2UserRecord, ULong> OAUTH2_APP_ID = createField(DSL.name("oauth2_app_id"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "A reference to the record in `oauth2_app`.");

    /**
     * The column <code>oagi.app_oauth2_user.sub</code>. `sub` claim defined in OIDC spec. This is a unique identifier of the subject in the provider.
     */
    public final TableField<AppOauth2UserRecord, String> SUB = createField(DSL.name("sub"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "`sub` claim defined in OIDC spec. This is a unique identifier of the subject in the provider.");

    /**
     * The column <code>oagi.app_oauth2_user.name</code>. `name` claim defined in OIDC spec.
     */
    public final TableField<AppOauth2UserRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(200), this, "`name` claim defined in OIDC spec.");

    /**
     * The column <code>oagi.app_oauth2_user.email</code>. `email` claim defined in OIDC spec.
     */
    public final TableField<AppOauth2UserRecord, String> EMAIL = createField(DSL.name("email"), org.jooq.impl.SQLDataType.VARCHAR(200), this, "`email` claim defined in OIDC spec.");

    /**
     * The column <code>oagi.app_oauth2_user.nickname</code>. `nickname` claim defined in OIDC spec.
     */
    public final TableField<AppOauth2UserRecord, String> NICKNAME = createField(DSL.name("nickname"), org.jooq.impl.SQLDataType.VARCHAR(200), this, "`nickname` claim defined in OIDC spec.");

    /**
     * The column <code>oagi.app_oauth2_user.preferred_username</code>. `preferred_username` claim defined in OIDC spec.
     */
    public final TableField<AppOauth2UserRecord, String> PREFERRED_USERNAME = createField(DSL.name("preferred_username"), org.jooq.impl.SQLDataType.VARCHAR(200), this, "`preferred_username` claim defined in OIDC spec.");

    /**
     * The column <code>oagi.app_oauth2_user.phone_number</code>. `phone_number` claim defined in OIDC spec.
     */
    public final TableField<AppOauth2UserRecord, String> PHONE_NUMBER = createField(DSL.name("phone_number"), org.jooq.impl.SQLDataType.VARCHAR(200), this, "`phone_number` claim defined in OIDC spec.");

    /**
     * The column <code>oagi.app_oauth2_user.creation_timestamp</code>. Timestamp when this record is created.
     */
    public final TableField<AppOauth2UserRecord, LocalDateTime> CREATION_TIMESTAMP = createField(DSL.name("creation_timestamp"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "Timestamp when this record is created.");

    /**
     * Create a <code>oagi.app_oauth2_user</code> table reference
     */
    public AppOauth2User() {
        this(DSL.name("app_oauth2_user"), null);
    }

    /**
     * Create an aliased <code>oagi.app_oauth2_user</code> table reference
     */
    public AppOauth2User(String alias) {
        this(DSL.name(alias), APP_OAUTH2_USER);
    }

    /**
     * Create an aliased <code>oagi.app_oauth2_user</code> table reference
     */
    public AppOauth2User(Name alias) {
        this(alias, APP_OAUTH2_USER);
    }

    private AppOauth2User(Name alias, Table<AppOauth2UserRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppOauth2User(Name alias, Table<AppOauth2UserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> AppOauth2User(Table<O> child, ForeignKey<O, AppOauth2UserRecord> key) {
        super(child, key, APP_OAUTH2_USER);
    }

    @Override
    public Schema getSchema() {
        return Oagi.OAGI;
    }

    @Override
    public Identity<AppOauth2UserRecord, ULong> getIdentity() {
        return Keys.IDENTITY_APP_OAUTH2_USER;
    }

    @Override
    public UniqueKey<AppOauth2UserRecord> getPrimaryKey() {
        return Keys.KEY_APP_OAUTH2_USER_PRIMARY;
    }

    @Override
    public List<UniqueKey<AppOauth2UserRecord>> getKeys() {
        return Arrays.<UniqueKey<AppOauth2UserRecord>>asList(Keys.KEY_APP_OAUTH2_USER_PRIMARY, Keys.KEY_APP_OAUTH2_USER_APP_OAUTH2_USER_UK1);
    }

    @Override
    public List<ForeignKey<AppOauth2UserRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AppOauth2UserRecord, ?>>asList(Keys.APP_OAUTH2_USER_APP_USER_ID_FK, Keys.APP_OAUTH2_USER_OAUTH2_APP_ID_FK);
    }

    public AppUser appUser() {
        return new AppUser(this, Keys.APP_OAUTH2_USER_APP_USER_ID_FK);
    }

    public Oauth2App oauth2App() {
        return new Oauth2App(this, Keys.APP_OAUTH2_USER_OAUTH2_APP_ID_FK);
    }

    @Override
    public AppOauth2User as(String alias) {
        return new AppOauth2User(DSL.name(alias), this);
    }

    @Override
    public AppOauth2User as(Name alias) {
        return new AppOauth2User(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppOauth2User rename(String name) {
        return new AppOauth2User(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppOauth2User rename(Name name) {
        return new AppOauth2User(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<ULong, ULong, ULong, String, String, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
