/*
 * This file is generated by jOOQ.
 */
package org.oagi.srt.entity.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.srt.entity.jooq.Indexes;
import org.oagi.srt.entity.jooq.Keys;
import org.oagi.srt.entity.jooq.Oagi;
import org.oagi.srt.entity.jooq.tables.records.BizCtxRuleRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizCtxRule extends TableImpl<BizCtxRuleRecord> {

    private static final long serialVersionUID = 192818985;

    /**
     * The reference instance of <code>oagi.biz_ctx_rule</code>
     */
    public static final BizCtxRule BIZ_CTX_RULE = new BizCtxRule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BizCtxRuleRecord> getRecordType() {
        return BizCtxRuleRecord.class;
    }

    /**
     * The column <code>oagi.biz_ctx_rule.biz_ctx_rule_id</code>.
     */
    public final TableField<BizCtxRuleRecord, ULong> BIZ_CTX_RULE_ID = createField("biz_ctx_rule_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>oagi.biz_ctx_rule.from_biz_ctx_id</code>.
     */
    public final TableField<BizCtxRuleRecord, ULong> FROM_BIZ_CTX_ID = createField("from_biz_ctx_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>oagi.biz_ctx_rule.top_level_bie_id</code>.
     */
    public final TableField<BizCtxRuleRecord, ULong> TOP_LEVEL_BIE_ID = createField("top_level_bie_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>oagi.biz_ctx_rule</code> table reference
     */
    public BizCtxRule() {
        this(DSL.name("biz_ctx_rule"), null);
    }

    /**
     * Create an aliased <code>oagi.biz_ctx_rule</code> table reference
     */
    public BizCtxRule(String alias) {
        this(DSL.name(alias), BIZ_CTX_RULE);
    }

    /**
     * Create an aliased <code>oagi.biz_ctx_rule</code> table reference
     */
    public BizCtxRule(Name alias) {
        this(alias, BIZ_CTX_RULE);
    }

    private BizCtxRule(Name alias, Table<BizCtxRuleRecord> aliased) {
        this(alias, aliased, null);
    }

    private BizCtxRule(Name alias, Table<BizCtxRuleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BizCtxRule(Table<O> child, ForeignKey<O, BizCtxRuleRecord> key) {
        super(child, key, BIZ_CTX_RULE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Oagi.OAGI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BIZ_CTX_RULE_FROM_BIZ_CTX_ID, Indexes.BIZ_CTX_RULE_PRIMARY, Indexes.BIZ_CTX_RULE_TOP_LEVEL_BIE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BizCtxRuleRecord> getPrimaryKey() {
        return Keys.KEY_BIZ_CTX_RULE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BizCtxRuleRecord>> getKeys() {
        return Arrays.<UniqueKey<BizCtxRuleRecord>>asList(Keys.KEY_BIZ_CTX_RULE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<BizCtxRuleRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<BizCtxRuleRecord, ?>>asList(Keys.BIZ_CTX_RULE_IBFK_1, Keys.BIZ_CTX_RULE_IBFK_2);
    }

    public BizCtx bizCtx() {
        return new BizCtx(this, Keys.BIZ_CTX_RULE_IBFK_1);
    }

    public TopLevelAbie topLevelAbie() {
        return new TopLevelAbie(this, Keys.BIZ_CTX_RULE_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizCtxRule as(String alias) {
        return new BizCtxRule(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizCtxRule as(Name alias) {
        return new BizCtxRule(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BizCtxRule rename(String name) {
        return new BizCtxRule(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BizCtxRule rename(Name name) {
        return new BizCtxRule(name, null);
    }
}
