/*
 * This file is generated by jOOQ.
 */
package org.oagi.srt.entity.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.srt.entity.jooq.Indexes;
import org.oagi.srt.entity.jooq.Keys;
import org.oagi.srt.entity.jooq.Oagi;
import org.oagi.srt.entity.jooq.tables.records.CdtPriRecord;


/**
 * This table stores the CDT primitives.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CdtPri extends TableImpl<CdtPriRecord> {

    private static final long serialVersionUID = -1807236684;

    /**
     * The reference instance of <code>oagi.cdt_pri</code>
     */
    public static final CdtPri CDT_PRI = new CdtPri();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CdtPriRecord> getRecordType() {
        return CdtPriRecord.class;
    }

    /**
     * The column <code>oagi.cdt_pri.cdt_pri_id</code>. Internal, primary database key.
     */
    public final TableField<CdtPriRecord, ULong> CDT_PRI_ID = createField("cdt_pri_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Internal, primary database key.");

    /**
     * The column <code>oagi.cdt_pri.name</code>. Name of the CDT primitive per the CCTS datatype catalog, e.g., Decimal.
     */
    public final TableField<CdtPriRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "Name of the CDT primitive per the CCTS datatype catalog, e.g., Decimal.");

    /**
     * Create a <code>oagi.cdt_pri</code> table reference
     */
    public CdtPri() {
        this(DSL.name("cdt_pri"), null);
    }

    /**
     * Create an aliased <code>oagi.cdt_pri</code> table reference
     */
    public CdtPri(String alias) {
        this(DSL.name(alias), CDT_PRI);
    }

    /**
     * Create an aliased <code>oagi.cdt_pri</code> table reference
     */
    public CdtPri(Name alias) {
        this(alias, CDT_PRI);
    }

    private CdtPri(Name alias, Table<CdtPriRecord> aliased) {
        this(alias, aliased, null);
    }

    private CdtPri(Name alias, Table<CdtPriRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("This table stores the CDT primitives."));
    }

    public <O extends Record> CdtPri(Table<O> child, ForeignKey<O, CdtPriRecord> key) {
        super(child, key, CDT_PRI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Oagi.OAGI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CDT_PRI_CDT_PRI_UK1, Indexes.CDT_PRI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CdtPriRecord, ULong> getIdentity() {
        return Keys.IDENTITY_CDT_PRI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CdtPriRecord> getPrimaryKey() {
        return Keys.KEY_CDT_PRI_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CdtPriRecord>> getKeys() {
        return Arrays.<UniqueKey<CdtPriRecord>>asList(Keys.KEY_CDT_PRI_PRIMARY, Keys.KEY_CDT_PRI_CDT_PRI_UK1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CdtPri as(String alias) {
        return new CdtPri(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CdtPri as(Name alias) {
        return new CdtPri(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CdtPri rename(String name) {
        return new CdtPri(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CdtPri rename(Name name) {
        return new CdtPri(name, null);
    }
}
