/*
 * This file is generated by jOOQ.
 */
package org.oagi.srt.entity.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.srt.entity.jooq.Keys;
import org.oagi.srt.entity.jooq.Oagi;
import org.oagi.srt.entity.jooq.tables.records.ModuleSetRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModuleSet extends TableImpl<ModuleSetRecord> {

    private static final long serialVersionUID = -845804592;

    /**
     * The reference instance of <code>oagi.module_set</code>
     */
    public static final ModuleSet MODULE_SET = new ModuleSet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ModuleSetRecord> getRecordType() {
        return ModuleSetRecord.class;
    }

    /**
     * The column <code>oagi.module_set.module_set_id</code>. Primary key.
     */
    public final TableField<ModuleSetRecord, ULong> MODULE_SET_ID = createField(DSL.name("module_set_id"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Primary key.");

    /**
     * The column <code>oagi.module_set.guid</code>. A globally unique identifier (GUID) of an SC. Per OAGIS, a GUID is of the form "oagis-id-" followed by a 32 Hex character sequence. Note that each SC is considered intrinsic to each DT, so a SC has a different GUID from the based SC, i.e., SC inherited from the based DT has a new, different GUID.
     */
    public final TableField<ModuleSetRecord, String> GUID = createField(DSL.name("guid"), org.jooq.impl.SQLDataType.VARCHAR(41).nullable(false), this, "A globally unique identifier (GUID) of an SC. Per OAGIS, a GUID is of the form \"oagis-id-\" followed by a 32 Hex character sequence. Note that each SC is considered intrinsic to each DT, so a SC has a different GUID from the based SC, i.e., SC inherited from the based DT has a new, different GUID.");

    /**
     * The column <code>oagi.module_set.name</code>. This is the name of the module set.
     */
    public final TableField<ModuleSetRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "This is the name of the module set.");

    /**
     * The column <code>oagi.module_set.description</code>. Description or explanation about the module set or use of the module set.
     */
    public final TableField<ModuleSetRecord, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.CLOB, this, "Description or explanation about the module set or use of the module set.");

    /**
     * The column <code>oagi.module_set.created_by</code>. Foreign key to the APP_USER table. It indicates the user who created this MODULE_SET.
     */
    public final TableField<ModuleSetRecord, ULong> CREATED_BY = createField(DSL.name("created_by"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Foreign key to the APP_USER table. It indicates the user who created this MODULE_SET.");

    /**
     * The column <code>oagi.module_set.last_updated_by</code>. Foreign key to the APP_USER table referring to the last user who updated the record.
     */
    public final TableField<ModuleSetRecord, ULong> LAST_UPDATED_BY = createField(DSL.name("last_updated_by"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Foreign key to the APP_USER table referring to the last user who updated the record.");

    /**
     * The column <code>oagi.module_set.creation_timestamp</code>. The timestamp when the record was first created.
     */
    public final TableField<ModuleSetRecord, LocalDateTime> CREATION_TIMESTAMP = createField(DSL.name("creation_timestamp"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "The timestamp when the record was first created.");

    /**
     * The column <code>oagi.module_set.last_update_timestamp</code>. The timestamp when the record was last updated.
     */
    public final TableField<ModuleSetRecord, LocalDateTime> LAST_UPDATE_TIMESTAMP = createField(DSL.name("last_update_timestamp"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "The timestamp when the record was last updated.");

    /**
     * Create a <code>oagi.module_set</code> table reference
     */
    public ModuleSet() {
        this(DSL.name("module_set"), null);
    }

    /**
     * Create an aliased <code>oagi.module_set</code> table reference
     */
    public ModuleSet(String alias) {
        this(DSL.name(alias), MODULE_SET);
    }

    /**
     * Create an aliased <code>oagi.module_set</code> table reference
     */
    public ModuleSet(Name alias) {
        this(alias, MODULE_SET);
    }

    private ModuleSet(Name alias, Table<ModuleSetRecord> aliased) {
        this(alias, aliased, null);
    }

    private ModuleSet(Name alias, Table<ModuleSetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> ModuleSet(Table<O> child, ForeignKey<O, ModuleSetRecord> key) {
        super(child, key, MODULE_SET);
    }

    @Override
    public Schema getSchema() {
        return Oagi.OAGI;
    }

    @Override
    public Identity<ModuleSetRecord, ULong> getIdentity() {
        return Keys.IDENTITY_MODULE_SET;
    }

    @Override
    public UniqueKey<ModuleSetRecord> getPrimaryKey() {
        return Keys.KEY_MODULE_SET_PRIMARY;
    }

    @Override
    public List<UniqueKey<ModuleSetRecord>> getKeys() {
        return Arrays.<UniqueKey<ModuleSetRecord>>asList(Keys.KEY_MODULE_SET_PRIMARY);
    }

    @Override
    public List<ForeignKey<ModuleSetRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ModuleSetRecord, ?>>asList(Keys.MODULE_SET_CREATED_BY_FK, Keys.MODULE_SET_LAST_UPDATED_BY_FK);
    }

    public AppUser moduleSetCreatedByFk() {
        return new AppUser(this, Keys.MODULE_SET_CREATED_BY_FK);
    }

    public AppUser moduleSetLastUpdatedByFk() {
        return new AppUser(this, Keys.MODULE_SET_LAST_UPDATED_BY_FK);
    }

    @Override
    public ModuleSet as(String alias) {
        return new ModuleSet(DSL.name(alias), this);
    }

    @Override
    public ModuleSet as(Name alias) {
        return new ModuleSet(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ModuleSet rename(String name) {
        return new ModuleSet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ModuleSet rename(Name name) {
        return new ModuleSet(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<ULong, String, String, String, ULong, ULong, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
