server:
  port: 9000
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://docker:3306/oagi?useSSL=false
    username: oagi
    password: oagi

  session:
    store-type: redis

  cache:
    type: redis

  redis:
    host: docker
    port: 6379


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.jdbc: DEBUG
    org.oagi.srt: TRACE