server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oagi?useSSL=false
    username: oagi
    password: oagi

  session:
    store-type: redis

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379


logging:
  level:
    org.springframework.security: DEBUG
    org.oagi.srt: DEBUG