version: "3"
services:
  db:
    image: oagi1docker/srt-repo:2.2.0
    container_name: score-repo
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql
  redis:
    image: redis:4
    container_name: score-redis
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: score_elasticsearch
    # restart: on-failure
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    logging:
        driver: "json-file"
        options:
            max-size: "10k"
            max-file: "10"
    ports:
      - 9200:9200
  logstash:
    build:
      context: .
      dockerfile: Dockerfile-logstash
    container_name: score_logstash
    # restart: on-failure
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ./volumes/logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./volumes/logstash/config/:/usr/share/logstash/config/
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: score_kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "SERVER_NAME=127.0.0.1"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      
volumes:
  db-volume:
  redis-volume:
