/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;
import org.oagi.score.repo.api.impl.jooq.entity.tables.AppGroup;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppGroupRecord extends UpdatableRecordImpl<AppGroupRecord> implements Record3<ULong, String, UInteger> {

    private static final long serialVersionUID = -1319187537;

    /**
     * Setter for <code>oagi.app_group.app_group_id</code>.
     */
    public void setAppGroupId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.app_group.app_group_id</code>.
     */
    public ULong getAppGroupId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.app_group.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.app_group.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.app_group.authority</code>.
     */
    public void setAuthority(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.app_group.authority</code>.
     */
    public UInteger getAuthority() {
        return (UInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<ULong, String, UInteger> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<ULong, String, UInteger> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return AppGroup.APP_GROUP.APP_GROUP_ID;
    }

    @Override
    public Field<String> field2() {
        return AppGroup.APP_GROUP.NAME;
    }

    @Override
    public Field<UInteger> field3() {
        return AppGroup.APP_GROUP.AUTHORITY;
    }

    @Override
    public ULong component1() {
        return getAppGroupId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UInteger component3() {
        return getAuthority();
    }

    @Override
    public ULong value1() {
        return getAppGroupId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public UInteger value3() {
        return getAuthority();
    }

    @Override
    public AppGroupRecord value1(ULong value) {
        setAppGroupId(value);
        return this;
    }

    @Override
    public AppGroupRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AppGroupRecord value3(UInteger value) {
        setAuthority(value);
        return this;
    }

    @Override
    public AppGroupRecord values(ULong value1, String value2, UInteger value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppGroupRecord
     */
    public AppGroupRecord() {
        super(AppGroup.APP_GROUP);
    }

    /**
     * Create a detached, initialised AppGroupRecord
     */
    public AppGroupRecord(ULong appGroupId, String name, UInteger authority) {
        super(AppGroup.APP_GROUP);

        set(0, appGroupId);
        set(1, name);
        set(2, authority);
    }
}
