/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.BbieBizterm;

import java.time.LocalDateTime;


/**
 * The bbie_bizterm table stores information about the aggregation between the
 * bbie_bizterm and BBIE. TODO: Placeholder, definition is missing.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BbieBiztermRecord extends UpdatableRecordImpl<BbieBiztermRecord> implements Record9<String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.bbie_bizterm.bbie_bizterm_id</code>. Primary,
     * internal database key.
     */
    public void setBbieBiztermId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.bbie_bizterm.bbie_bizterm_id</code>. Primary,
     * internal database key.
     */
    public String getBbieBiztermId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>oagi.bbie_bizterm.bcc_bizterm_id</code>. An internal ID
     * of the bcc_business_term record.
     */
    public void setBccBiztermId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.bbie_bizterm.bcc_bizterm_id</code>. An internal ID
     * of the bcc_business_term record.
     */
    public String getBccBiztermId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.bbie_bizterm.bbie_id</code>. An internal ID of the
     * associated BBIE
     */
    public void setBbieId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.bbie_bizterm.bbie_id</code>. An internal ID of the
     * associated BBIE
     */
    public String getBbieId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oagi.bbie_bizterm.primary_indicator</code>. The
     * indicator shows if the business term is primary for the assigned BBIE.
     */
    public void setPrimaryIndicator(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.bbie_bizterm.primary_indicator</code>. The
     * indicator shows if the business term is primary for the assigned BBIE.
     */
    public String getPrimaryIndicator() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oagi.bbie_bizterm.type_code</code>. The type code of the
     * assignment.
     */
    public void setTypeCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.bbie_bizterm.type_code</code>. The type code of the
     * assignment.
     */
    public String getTypeCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.bbie_bizterm.created_by</code>. A foreign key
     * referring to the user who creates the BBIE_BIZTERM record. The creator of
     * the ASBIE_BIZTERM is also its owner by default.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.bbie_bizterm.created_by</code>. A foreign key
     * referring to the user who creates the BBIE_BIZTERM record. The creator of
     * the ASBIE_BIZTERM is also its owner by default.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oagi.bbie_bizterm.last_updated_by</code>. A foreign key
     * referring to the last user who has updated the BBIE_BIZTERM record. This
     * may be the user who is in the same group as the creator.
     */
    public void setLastUpdatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.bbie_bizterm.last_updated_by</code>. A foreign key
     * referring to the last user who has updated the BBIE_BIZTERM record. This
     * may be the user who is in the same group as the creator.
     */
    public String getLastUpdatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oagi.bbie_bizterm.creation_timestamp</code>. Timestamp
     * when the bbie_bizterm record was first created.
     */
    public void setCreationTimestamp(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.bbie_bizterm.creation_timestamp</code>. Timestamp
     * when the bbie_bizterm record was first created.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>oagi.bbie_bizterm.last_update_timestamp</code>. The
     * timestamp when the bbie_bizterm was last updated.
     */
    public void setLastUpdateTimestamp(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.bbie_bizterm.last_update_timestamp</code>. The
     * timestamp when the bbie_bizterm was last updated.
     */
    public LocalDateTime getLastUpdateTimestamp() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return BbieBizterm.BBIE_BIZTERM.BBIE_BIZTERM_ID;
    }

    @Override
    public Field<String> field2() {
        return BbieBizterm.BBIE_BIZTERM.BCC_BIZTERM_ID;
    }

    @Override
    public Field<String> field3() {
        return BbieBizterm.BBIE_BIZTERM.BBIE_ID;
    }

    @Override
    public Field<String> field4() {
        return BbieBizterm.BBIE_BIZTERM.PRIMARY_INDICATOR;
    }

    @Override
    public Field<String> field5() {
        return BbieBizterm.BBIE_BIZTERM.TYPE_CODE;
    }

    @Override
    public Field<String> field6() {
        return BbieBizterm.BBIE_BIZTERM.CREATED_BY;
    }

    @Override
    public Field<String> field7() {
        return BbieBizterm.BBIE_BIZTERM.LAST_UPDATED_BY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return BbieBizterm.BBIE_BIZTERM.CREATION_TIMESTAMP;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return BbieBizterm.BBIE_BIZTERM.LAST_UPDATE_TIMESTAMP;
    }

    @Override
    public String component1() {
        return getBbieBiztermId();
    }

    @Override
    public String component2() {
        return getBccBiztermId();
    }

    @Override
    public String component3() {
        return getBbieId();
    }

    @Override
    public String component4() {
        return getPrimaryIndicator();
    }

    @Override
    public String component5() {
        return getTypeCode();
    }

    @Override
    public String component6() {
        return getCreatedBy();
    }

    @Override
    public String component7() {
        return getLastUpdatedBy();
    }

    @Override
    public LocalDateTime component8() {
        return getCreationTimestamp();
    }

    @Override
    public LocalDateTime component9() {
        return getLastUpdateTimestamp();
    }

    @Override
    public String value1() {
        return getBbieBiztermId();
    }

    @Override
    public String value2() {
        return getBccBiztermId();
    }

    @Override
    public String value3() {
        return getBbieId();
    }

    @Override
    public String value4() {
        return getPrimaryIndicator();
    }

    @Override
    public String value5() {
        return getTypeCode();
    }

    @Override
    public String value6() {
        return getCreatedBy();
    }

    @Override
    public String value7() {
        return getLastUpdatedBy();
    }

    @Override
    public LocalDateTime value8() {
        return getCreationTimestamp();
    }

    @Override
    public LocalDateTime value9() {
        return getLastUpdateTimestamp();
    }

    @Override
    public BbieBiztermRecord value1(String value) {
        setBbieBiztermId(value);
        return this;
    }

    @Override
    public BbieBiztermRecord value2(String value) {
        setBccBiztermId(value);
        return this;
    }

    @Override
    public BbieBiztermRecord value3(String value) {
        setBbieId(value);
        return this;
    }

    @Override
    public BbieBiztermRecord value4(String value) {
        setPrimaryIndicator(value);
        return this;
    }

    @Override
    public BbieBiztermRecord value5(String value) {
        setTypeCode(value);
        return this;
    }

    @Override
    public BbieBiztermRecord value6(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public BbieBiztermRecord value7(String value) {
        setLastUpdatedBy(value);
        return this;
    }

    @Override
    public BbieBiztermRecord value8(LocalDateTime value) {
        setCreationTimestamp(value);
        return this;
    }

    @Override
    public BbieBiztermRecord value9(LocalDateTime value) {
        setLastUpdateTimestamp(value);
        return this;
    }

    @Override
    public BbieBiztermRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BbieBiztermRecord
     */
    public BbieBiztermRecord() {
        super(BbieBizterm.BBIE_BIZTERM);
    }

    /**
     * Create a detached, initialised BbieBiztermRecord
     */
    public BbieBiztermRecord(String bbieBiztermId, String bccBiztermId, String bbieId, String primaryIndicator, String typeCode, String createdBy, String lastUpdatedBy, LocalDateTime creationTimestamp, LocalDateTime lastUpdateTimestamp) {
        super(BbieBizterm.BBIE_BIZTERM);

        setBbieBiztermId(bbieBiztermId);
        setBccBiztermId(bccBiztermId);
        setBbieId(bbieId);
        setPrimaryIndicator(primaryIndicator);
        setTypeCode(typeCode);
        setCreatedBy(createdBy);
        setLastUpdatedBy(lastUpdatedBy);
        setCreationTimestamp(creationTimestamp);
        setLastUpdateTimestamp(lastUpdateTimestamp);
    }
}
