/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.CdtScRefSpec;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CdtScRefSpecRecord extends UpdatableRecordImpl<CdtScRefSpecRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.cdt_sc_ref_spec.cdt_sc_ref_spec_id</code>. Primary,
     * internal database key.
     */
    public void setCdtScRefSpecId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.cdt_sc_ref_spec.cdt_sc_ref_spec_id</code>. Primary,
     * internal database key.
     */
    public String getCdtScRefSpecId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>oagi.cdt_sc_ref_spec.cdt_sc_id</code>.
     */
    public void setCdtScId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.cdt_sc_ref_spec.cdt_sc_id</code>.
     */
    public String getCdtScId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.cdt_sc_ref_spec.ref_spec_id</code>.
     */
    public void setRefSpecId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.cdt_sc_ref_spec.ref_spec_id</code>.
     */
    public String getRefSpecId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CdtScRefSpec.CDT_SC_REF_SPEC.CDT_SC_REF_SPEC_ID;
    }

    @Override
    public Field<String> field2() {
        return CdtScRefSpec.CDT_SC_REF_SPEC.CDT_SC_ID;
    }

    @Override
    public Field<String> field3() {
        return CdtScRefSpec.CDT_SC_REF_SPEC.REF_SPEC_ID;
    }

    @Override
    public String component1() {
        return getCdtScRefSpecId();
    }

    @Override
    public String component2() {
        return getCdtScId();
    }

    @Override
    public String component3() {
        return getRefSpecId();
    }

    @Override
    public String value1() {
        return getCdtScRefSpecId();
    }

    @Override
    public String value2() {
        return getCdtScId();
    }

    @Override
    public String value3() {
        return getRefSpecId();
    }

    @Override
    public CdtScRefSpecRecord value1(String value) {
        setCdtScRefSpecId(value);
        return this;
    }

    @Override
    public CdtScRefSpecRecord value2(String value) {
        setCdtScId(value);
        return this;
    }

    @Override
    public CdtScRefSpecRecord value3(String value) {
        setRefSpecId(value);
        return this;
    }

    @Override
    public CdtScRefSpecRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CdtScRefSpecRecord
     */
    public CdtScRefSpecRecord() {
        super(CdtScRefSpec.CDT_SC_REF_SPEC);
    }

    /**
     * Create a detached, initialised CdtScRefSpecRecord
     */
    public CdtScRefSpecRecord(String cdtScRefSpecId, String cdtScId, String refSpecId) {
        super(CdtScRefSpec.CDT_SC_REF_SPEC);

        setCdtScRefSpecId(cdtScRefSpecId);
        setCdtScId(cdtScId);
        setRefSpecId(refSpecId);
    }
}
