/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.CodeListValueManifest;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeListValueManifestRecord extends UpdatableRecordImpl<CodeListValueManifestRecord> implements Record9<String, String, String, String, String, Byte, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>oagi.code_list_value_manifest.code_list_value_manifest_id</code>.
     * Primary, internal database key.
     */
    public void setCodeListValueManifestId(String value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>oagi.code_list_value_manifest.code_list_value_manifest_id</code>.
     * Primary, internal database key.
     */
    public String getCodeListValueManifestId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>oagi.code_list_value_manifest.release_id</code>.
     */
    public void setReleaseId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.code_list_value_manifest.release_id</code>.
     */
    public String getReleaseId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.code_list_value_manifest.code_list_value_id</code>.
     */
    public void setCodeListValueId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.code_list_value_manifest.code_list_value_id</code>.
     */
    public String getCodeListValueId() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>oagi.code_list_value_manifest.code_list_manifest_id</code>.
     */
    public void setCodeListManifestId(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>oagi.code_list_value_manifest.code_list_manifest_id</code>.
     */
    public String getCodeListManifestId() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>oagi.code_list_value_manifest.based_code_list_value_manifest_id</code>.
     */
    public void setBasedCodeListValueManifestId(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>oagi.code_list_value_manifest.based_code_list_value_manifest_id</code>.
     */
    public String getBasedCodeListValueManifestId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.code_list_value_manifest.conflict</code>. This
     * indicates that there is a conflict between self and relationship.
     */
    public void setConflict(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.code_list_value_manifest.conflict</code>. This
     * indicates that there is a conflict between self and relationship.
     */
    public Byte getConflict() {
        return (Byte) get(5);
    }

    /**
     * Setter for
     * <code>oagi.code_list_value_manifest.replacement_code_list_value_manifest_id</code>.
     * This refers to a replacement manifest if the record is deprecated.
     */
    public void setReplacementCodeListValueManifestId(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>oagi.code_list_value_manifest.replacement_code_list_value_manifest_id</code>.
     * This refers to a replacement manifest if the record is deprecated.
     */
    public String getReplacementCodeListValueManifestId() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>oagi.code_list_value_manifest.prev_code_list_value_manifest_id</code>.
     */
    public void setPrevCodeListValueManifestId(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>oagi.code_list_value_manifest.prev_code_list_value_manifest_id</code>.
     */
    public String getPrevCodeListValueManifestId() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>oagi.code_list_value_manifest.next_code_list_value_manifest_id</code>.
     */
    public void setNextCodeListValueManifestId(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>oagi.code_list_value_manifest.next_code_list_value_manifest_id</code>.
     */
    public String getNextCodeListValueManifestId() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, String, String, String, String, Byte, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, String, String, String, String, Byte, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CodeListValueManifest.CODE_LIST_VALUE_MANIFEST.CODE_LIST_VALUE_MANIFEST_ID;
    }

    @Override
    public Field<String> field2() {
        return CodeListValueManifest.CODE_LIST_VALUE_MANIFEST.RELEASE_ID;
    }

    @Override
    public Field<String> field3() {
        return CodeListValueManifest.CODE_LIST_VALUE_MANIFEST.CODE_LIST_VALUE_ID;
    }

    @Override
    public Field<String> field4() {
        return CodeListValueManifest.CODE_LIST_VALUE_MANIFEST.CODE_LIST_MANIFEST_ID;
    }

    @Override
    public Field<String> field5() {
        return CodeListValueManifest.CODE_LIST_VALUE_MANIFEST.BASED_CODE_LIST_VALUE_MANIFEST_ID;
    }

    @Override
    public Field<Byte> field6() {
        return CodeListValueManifest.CODE_LIST_VALUE_MANIFEST.CONFLICT;
    }

    @Override
    public Field<String> field7() {
        return CodeListValueManifest.CODE_LIST_VALUE_MANIFEST.REPLACEMENT_CODE_LIST_VALUE_MANIFEST_ID;
    }

    @Override
    public Field<String> field8() {
        return CodeListValueManifest.CODE_LIST_VALUE_MANIFEST.PREV_CODE_LIST_VALUE_MANIFEST_ID;
    }

    @Override
    public Field<String> field9() {
        return CodeListValueManifest.CODE_LIST_VALUE_MANIFEST.NEXT_CODE_LIST_VALUE_MANIFEST_ID;
    }

    @Override
    public String component1() {
        return getCodeListValueManifestId();
    }

    @Override
    public String component2() {
        return getReleaseId();
    }

    @Override
    public String component3() {
        return getCodeListValueId();
    }

    @Override
    public String component4() {
        return getCodeListManifestId();
    }

    @Override
    public String component5() {
        return getBasedCodeListValueManifestId();
    }

    @Override
    public Byte component6() {
        return getConflict();
    }

    @Override
    public String component7() {
        return getReplacementCodeListValueManifestId();
    }

    @Override
    public String component8() {
        return getPrevCodeListValueManifestId();
    }

    @Override
    public String component9() {
        return getNextCodeListValueManifestId();
    }

    @Override
    public String value1() {
        return getCodeListValueManifestId();
    }

    @Override
    public String value2() {
        return getReleaseId();
    }

    @Override
    public String value3() {
        return getCodeListValueId();
    }

    @Override
    public String value4() {
        return getCodeListManifestId();
    }

    @Override
    public String value5() {
        return getBasedCodeListValueManifestId();
    }

    @Override
    public Byte value6() {
        return getConflict();
    }

    @Override
    public String value7() {
        return getReplacementCodeListValueManifestId();
    }

    @Override
    public String value8() {
        return getPrevCodeListValueManifestId();
    }

    @Override
    public String value9() {
        return getNextCodeListValueManifestId();
    }

    @Override
    public CodeListValueManifestRecord value1(String value) {
        setCodeListValueManifestId(value);
        return this;
    }

    @Override
    public CodeListValueManifestRecord value2(String value) {
        setReleaseId(value);
        return this;
    }

    @Override
    public CodeListValueManifestRecord value3(String value) {
        setCodeListValueId(value);
        return this;
    }

    @Override
    public CodeListValueManifestRecord value4(String value) {
        setCodeListManifestId(value);
        return this;
    }

    @Override
    public CodeListValueManifestRecord value5(String value) {
        setBasedCodeListValueManifestId(value);
        return this;
    }

    @Override
    public CodeListValueManifestRecord value6(Byte value) {
        setConflict(value);
        return this;
    }

    @Override
    public CodeListValueManifestRecord value7(String value) {
        setReplacementCodeListValueManifestId(value);
        return this;
    }

    @Override
    public CodeListValueManifestRecord value8(String value) {
        setPrevCodeListValueManifestId(value);
        return this;
    }

    @Override
    public CodeListValueManifestRecord value9(String value) {
        setNextCodeListValueManifestId(value);
        return this;
    }

    @Override
    public CodeListValueManifestRecord values(String value1, String value2, String value3, String value4, String value5, Byte value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeListValueManifestRecord
     */
    public CodeListValueManifestRecord() {
        super(CodeListValueManifest.CODE_LIST_VALUE_MANIFEST);
    }

    /**
     * Create a detached, initialised CodeListValueManifestRecord
     */
    public CodeListValueManifestRecord(String codeListValueManifestId, String releaseId, String codeListValueId, String codeListManifestId, String basedCodeListValueManifestId, Byte conflict, String replacementCodeListValueManifestId, String prevCodeListValueManifestId, String nextCodeListValueManifestId) {
        super(CodeListValueManifest.CODE_LIST_VALUE_MANIFEST);

        setCodeListValueManifestId(codeListValueManifestId);
        setReleaseId(releaseId);
        setCodeListValueId(codeListValueId);
        setCodeListManifestId(codeListManifestId);
        setBasedCodeListValueManifestId(basedCodeListValueManifestId);
        setConflict(conflict);
        setReplacementCodeListValueManifestId(replacementCodeListValueManifestId);
        setPrevCodeListValueManifestId(prevCodeListValueManifestId);
        setNextCodeListValueManifestId(nextCodeListValueManifestId);
    }
}
