/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.CtxSchemeValue;


/**
 * This table stores the context scheme values for a particular context scheme
 * in the CTX_SCHEME table.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtxSchemeValueRecord extends UpdatableRecordImpl<CtxSchemeValueRecord> implements Record5<String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.ctx_scheme_value.ctx_scheme_value_id</code>.
     * Primary, internal database key.
     */
    public void setCtxSchemeValueId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.ctx_scheme_value.ctx_scheme_value_id</code>.
     * Primary, internal database key.
     */
    public String getCtxSchemeValueId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>oagi.ctx_scheme_value.guid</code>. A globally unique
     * identifier (GUID).
     */
    public void setGuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.ctx_scheme_value.guid</code>. A globally unique
     * identifier (GUID).
     */
    public String getGuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.ctx_scheme_value.value</code>. A short value for
     * the scheme value similar to the code list value.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.ctx_scheme_value.value</code>. A short value for
     * the scheme value similar to the code list value.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oagi.ctx_scheme_value.meaning</code>. The description,
     * explanatiion of the scheme value.
     */
    public void setMeaning(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.ctx_scheme_value.meaning</code>. The description,
     * explanatiion of the scheme value.
     */
    public String getMeaning() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oagi.ctx_scheme_value.owner_ctx_scheme_id</code>.
     * Foreign key to the CTX_SCHEME table. It identifies the context scheme, to
     * which this scheme value belongs.
     */
    public void setOwnerCtxSchemeId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.ctx_scheme_value.owner_ctx_scheme_id</code>.
     * Foreign key to the CTX_SCHEME table. It identifies the context scheme, to
     * which this scheme value belongs.
     */
    public String getOwnerCtxSchemeId() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CtxSchemeValue.CTX_SCHEME_VALUE.CTX_SCHEME_VALUE_ID;
    }

    @Override
    public Field<String> field2() {
        return CtxSchemeValue.CTX_SCHEME_VALUE.GUID;
    }

    @Override
    public Field<String> field3() {
        return CtxSchemeValue.CTX_SCHEME_VALUE.VALUE;
    }

    @Override
    public Field<String> field4() {
        return CtxSchemeValue.CTX_SCHEME_VALUE.MEANING;
    }

    @Override
    public Field<String> field5() {
        return CtxSchemeValue.CTX_SCHEME_VALUE.OWNER_CTX_SCHEME_ID;
    }

    @Override
    public String component1() {
        return getCtxSchemeValueId();
    }

    @Override
    public String component2() {
        return getGuid();
    }

    @Override
    public String component3() {
        return getValue();
    }

    @Override
    public String component4() {
        return getMeaning();
    }

    @Override
    public String component5() {
        return getOwnerCtxSchemeId();
    }

    @Override
    public String value1() {
        return getCtxSchemeValueId();
    }

    @Override
    public String value2() {
        return getGuid();
    }

    @Override
    public String value3() {
        return getValue();
    }

    @Override
    public String value4() {
        return getMeaning();
    }

    @Override
    public String value5() {
        return getOwnerCtxSchemeId();
    }

    @Override
    public CtxSchemeValueRecord value1(String value) {
        setCtxSchemeValueId(value);
        return this;
    }

    @Override
    public CtxSchemeValueRecord value2(String value) {
        setGuid(value);
        return this;
    }

    @Override
    public CtxSchemeValueRecord value3(String value) {
        setValue(value);
        return this;
    }

    @Override
    public CtxSchemeValueRecord value4(String value) {
        setMeaning(value);
        return this;
    }

    @Override
    public CtxSchemeValueRecord value5(String value) {
        setOwnerCtxSchemeId(value);
        return this;
    }

    @Override
    public CtxSchemeValueRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CtxSchemeValueRecord
     */
    public CtxSchemeValueRecord() {
        super(CtxSchemeValue.CTX_SCHEME_VALUE);
    }

    /**
     * Create a detached, initialised CtxSchemeValueRecord
     */
    public CtxSchemeValueRecord(String ctxSchemeValueId, String guid, String value, String meaning, String ownerCtxSchemeId) {
        super(CtxSchemeValue.CTX_SCHEME_VALUE);

        setCtxSchemeValueId(ctxSchemeValueId);
        setGuid(guid);
        setValue(value);
        setMeaning(meaning);
        setOwnerCtxSchemeId(ownerCtxSchemeId);
    }
}
