/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.XbtManifest;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class XbtManifestRecord extends UpdatableRecordImpl<XbtManifestRecord> implements Record7<String, String, String, Byte, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.xbt_manifest.xbt_manifest_id</code>. Primary,
     * internal database key.
     */
    public void setXbtManifestId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.xbt_manifest.xbt_manifest_id</code>. Primary,
     * internal database key.
     */
    public String getXbtManifestId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>oagi.xbt_manifest.release_id</code>.
     */
    public void setReleaseId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.xbt_manifest.release_id</code>.
     */
    public String getReleaseId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.xbt_manifest.xbt_id</code>.
     */
    public void setXbtId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.xbt_manifest.xbt_id</code>.
     */
    public String getXbtId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oagi.xbt_manifest.conflict</code>. This indicates that
     * there is a conflict between self and relationship.
     */
    public void setConflict(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.xbt_manifest.conflict</code>. This indicates that
     * there is a conflict between self and relationship.
     */
    public Byte getConflict() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>oagi.xbt_manifest.log_id</code>. A foreign key pointed
     * to a log for the current record.
     */
    public void setLogId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.xbt_manifest.log_id</code>. A foreign key pointed
     * to a log for the current record.
     */
    public String getLogId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.xbt_manifest.prev_xbt_manifest_id</code>.
     */
    public void setPrevXbtManifestId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.xbt_manifest.prev_xbt_manifest_id</code>.
     */
    public String getPrevXbtManifestId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oagi.xbt_manifest.next_xbt_manifest_id</code>.
     */
    public void setNextXbtManifestId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.xbt_manifest.next_xbt_manifest_id</code>.
     */
    public String getNextXbtManifestId() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, Byte, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, Byte, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return XbtManifest.XBT_MANIFEST.XBT_MANIFEST_ID;
    }

    @Override
    public Field<String> field2() {
        return XbtManifest.XBT_MANIFEST.RELEASE_ID;
    }

    @Override
    public Field<String> field3() {
        return XbtManifest.XBT_MANIFEST.XBT_ID;
    }

    @Override
    public Field<Byte> field4() {
        return XbtManifest.XBT_MANIFEST.CONFLICT;
    }

    @Override
    public Field<String> field5() {
        return XbtManifest.XBT_MANIFEST.LOG_ID;
    }

    @Override
    public Field<String> field6() {
        return XbtManifest.XBT_MANIFEST.PREV_XBT_MANIFEST_ID;
    }

    @Override
    public Field<String> field7() {
        return XbtManifest.XBT_MANIFEST.NEXT_XBT_MANIFEST_ID;
    }

    @Override
    public String component1() {
        return getXbtManifestId();
    }

    @Override
    public String component2() {
        return getReleaseId();
    }

    @Override
    public String component3() {
        return getXbtId();
    }

    @Override
    public Byte component4() {
        return getConflict();
    }

    @Override
    public String component5() {
        return getLogId();
    }

    @Override
    public String component6() {
        return getPrevXbtManifestId();
    }

    @Override
    public String component7() {
        return getNextXbtManifestId();
    }

    @Override
    public String value1() {
        return getXbtManifestId();
    }

    @Override
    public String value2() {
        return getReleaseId();
    }

    @Override
    public String value3() {
        return getXbtId();
    }

    @Override
    public Byte value4() {
        return getConflict();
    }

    @Override
    public String value5() {
        return getLogId();
    }

    @Override
    public String value6() {
        return getPrevXbtManifestId();
    }

    @Override
    public String value7() {
        return getNextXbtManifestId();
    }

    @Override
    public XbtManifestRecord value1(String value) {
        setXbtManifestId(value);
        return this;
    }

    @Override
    public XbtManifestRecord value2(String value) {
        setReleaseId(value);
        return this;
    }

    @Override
    public XbtManifestRecord value3(String value) {
        setXbtId(value);
        return this;
    }

    @Override
    public XbtManifestRecord value4(Byte value) {
        setConflict(value);
        return this;
    }

    @Override
    public XbtManifestRecord value5(String value) {
        setLogId(value);
        return this;
    }

    @Override
    public XbtManifestRecord value6(String value) {
        setPrevXbtManifestId(value);
        return this;
    }

    @Override
    public XbtManifestRecord value7(String value) {
        setNextXbtManifestId(value);
        return this;
    }

    @Override
    public XbtManifestRecord values(String value1, String value2, String value3, Byte value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached XbtManifestRecord
     */
    public XbtManifestRecord() {
        super(XbtManifest.XBT_MANIFEST);
    }

    /**
     * Create a detached, initialised XbtManifestRecord
     */
    public XbtManifestRecord(String xbtManifestId, String releaseId, String xbtId, Byte conflict, String logId, String prevXbtManifestId, String nextXbtManifestId) {
        super(XbtManifest.XBT_MANIFEST);

        setXbtManifestId(xbtManifestId);
        setReleaseId(releaseId);
        setXbtId(xbtId);
        setConflict(conflict);
        setLogId(logId);
        setPrevXbtManifestId(prevXbtManifestId);
        setNextXbtManifestId(nextXbtManifestId);
    }
}
