/*
 * This file is generated by jOOQ.
 */
package org.oagi.srt.entity.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.srt.entity.jooq.tables.AsccpManifest;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AsccpManifestRecord extends UpdatableRecordImpl<AsccpManifestRecord> implements Record5<ULong, ULong, ULong, ULong, ULong> {

    private static final long serialVersionUID = 1857832842;

    /**
     * Setter for <code>oagi.asccp_manifest.asccp_manifest_id</code>.
     */
    public void setAsccpManifestId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.asccp_manifest.asccp_manifest_id</code>.
     */
    public ULong getAsccpManifestId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.asccp_manifest.release_id</code>.
     */
    public void setReleaseId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.asccp_manifest.release_id</code>.
     */
    public ULong getReleaseId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.asccp_manifest.module_id</code>.
     */
    public void setModuleId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.asccp_manifest.module_id</code>.
     */
    public ULong getModuleId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.asccp_manifest.asccp_id</code>.
     */
    public void setAsccpId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.asccp_manifest.asccp_id</code>.
     */
    public ULong getAsccpId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.asccp_manifest.role_of_acc_manifest_id</code>.
     */
    public void setRoleOfAccManifestId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.asccp_manifest.role_of_acc_manifest_id</code>.
     */
    public ULong getRoleOfAccManifestId() {
        return (ULong) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<ULong, ULong, ULong, ULong, ULong> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<ULong, ULong, ULong, ULong, ULong> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return AsccpManifest.ASCCP_MANIFEST.ASCCP_MANIFEST_ID;
    }

    @Override
    public Field<ULong> field2() {
        return AsccpManifest.ASCCP_MANIFEST.RELEASE_ID;
    }

    @Override
    public Field<ULong> field3() {
        return AsccpManifest.ASCCP_MANIFEST.MODULE_ID;
    }

    @Override
    public Field<ULong> field4() {
        return AsccpManifest.ASCCP_MANIFEST.ASCCP_ID;
    }

    @Override
    public Field<ULong> field5() {
        return AsccpManifest.ASCCP_MANIFEST.ROLE_OF_ACC_MANIFEST_ID;
    }

    @Override
    public ULong component1() {
        return getAsccpManifestId();
    }

    @Override
    public ULong component2() {
        return getReleaseId();
    }

    @Override
    public ULong component3() {
        return getModuleId();
    }

    @Override
    public ULong component4() {
        return getAsccpId();
    }

    @Override
    public ULong component5() {
        return getRoleOfAccManifestId();
    }

    @Override
    public ULong value1() {
        return getAsccpManifestId();
    }

    @Override
    public ULong value2() {
        return getReleaseId();
    }

    @Override
    public ULong value3() {
        return getModuleId();
    }

    @Override
    public ULong value4() {
        return getAsccpId();
    }

    @Override
    public ULong value5() {
        return getRoleOfAccManifestId();
    }

    @Override
    public AsccpManifestRecord value1(ULong value) {
        setAsccpManifestId(value);
        return this;
    }

    @Override
    public AsccpManifestRecord value2(ULong value) {
        setReleaseId(value);
        return this;
    }

    @Override
    public AsccpManifestRecord value3(ULong value) {
        setModuleId(value);
        return this;
    }

    @Override
    public AsccpManifestRecord value4(ULong value) {
        setAsccpId(value);
        return this;
    }

    @Override
    public AsccpManifestRecord value5(ULong value) {
        setRoleOfAccManifestId(value);
        return this;
    }

    @Override
    public AsccpManifestRecord values(ULong value1, ULong value2, ULong value3, ULong value4, ULong value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AsccpManifestRecord
     */
    public AsccpManifestRecord() {
        super(AsccpManifest.ASCCP_MANIFEST);
    }

    /**
     * Create a detached, initialised AsccpManifestRecord
     */
    public AsccpManifestRecord(ULong asccpManifestId, ULong releaseId, ULong moduleId, ULong asccpId, ULong roleOfAccManifestId) {
        super(AsccpManifest.ASCCP_MANIFEST);

        set(0, asccpManifestId);
        set(1, releaseId);
        set(2, moduleId);
        set(3, asccpId);
        set(4, roleOfAccManifestId);
    }
}
