/*
 * This file is generated by jOOQ.
 */
package org.oagi.srt.entity.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.srt.entity.jooq.tables.AsccpReleaseManifest;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AsccpReleaseManifestRecord extends UpdatableRecordImpl<AsccpReleaseManifestRecord> implements Record5<ULong, ULong, ULong, ULong, ULong> {

    private static final long serialVersionUID = 2135953340;

    /**
     * Setter for <code>oagi.asccp_release_manifest.asccp_release_manifest_id</code>.
     */
    public void setAsccpReleaseManifestId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.asccp_release_manifest.asccp_release_manifest_id</code>.
     */
    public ULong getAsccpReleaseManifestId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.asccp_release_manifest.release_id</code>.
     */
    public void setReleaseId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.asccp_release_manifest.release_id</code>.
     */
    public ULong getReleaseId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.asccp_release_manifest.module_id</code>.
     */
    public void setModuleId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.asccp_release_manifest.module_id</code>.
     */
    public ULong getModuleId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.asccp_release_manifest.asccp_id</code>.
     */
    public void setAsccpId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.asccp_release_manifest.asccp_id</code>.
     */
    public ULong getAsccpId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.asccp_release_manifest.role_of_acc_id</code>.
     */
    public void setRoleOfAccId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.asccp_release_manifest.role_of_acc_id</code>.
     */
    public ULong getRoleOfAccId() {
        return (ULong) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<ULong, ULong, ULong, ULong, ULong> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<ULong, ULong, ULong, ULong, ULong> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return AsccpReleaseManifest.ASCCP_RELEASE_MANIFEST.ASCCP_RELEASE_MANIFEST_ID;
    }

    @Override
    public Field<ULong> field2() {
        return AsccpReleaseManifest.ASCCP_RELEASE_MANIFEST.RELEASE_ID;
    }

    @Override
    public Field<ULong> field3() {
        return AsccpReleaseManifest.ASCCP_RELEASE_MANIFEST.MODULE_ID;
    }

    @Override
    public Field<ULong> field4() {
        return AsccpReleaseManifest.ASCCP_RELEASE_MANIFEST.ASCCP_ID;
    }

    @Override
    public Field<ULong> field5() {
        return AsccpReleaseManifest.ASCCP_RELEASE_MANIFEST.ROLE_OF_ACC_ID;
    }

    @Override
    public ULong component1() {
        return getAsccpReleaseManifestId();
    }

    @Override
    public ULong component2() {
        return getReleaseId();
    }

    @Override
    public ULong component3() {
        return getModuleId();
    }

    @Override
    public ULong component4() {
        return getAsccpId();
    }

    @Override
    public ULong component5() {
        return getRoleOfAccId();
    }

    @Override
    public ULong value1() {
        return getAsccpReleaseManifestId();
    }

    @Override
    public ULong value2() {
        return getReleaseId();
    }

    @Override
    public ULong value3() {
        return getModuleId();
    }

    @Override
    public ULong value4() {
        return getAsccpId();
    }

    @Override
    public ULong value5() {
        return getRoleOfAccId();
    }

    @Override
    public AsccpReleaseManifestRecord value1(ULong value) {
        setAsccpReleaseManifestId(value);
        return this;
    }

    @Override
    public AsccpReleaseManifestRecord value2(ULong value) {
        setReleaseId(value);
        return this;
    }

    @Override
    public AsccpReleaseManifestRecord value3(ULong value) {
        setModuleId(value);
        return this;
    }

    @Override
    public AsccpReleaseManifestRecord value4(ULong value) {
        setAsccpId(value);
        return this;
    }

    @Override
    public AsccpReleaseManifestRecord value5(ULong value) {
        setRoleOfAccId(value);
        return this;
    }

    @Override
    public AsccpReleaseManifestRecord values(ULong value1, ULong value2, ULong value3, ULong value4, ULong value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AsccpReleaseManifestRecord
     */
    public AsccpReleaseManifestRecord() {
        super(AsccpReleaseManifest.ASCCP_RELEASE_MANIFEST);
    }

    /**
     * Create a detached, initialised AsccpReleaseManifestRecord
     */
    public AsccpReleaseManifestRecord(ULong asccpReleaseManifestId, ULong releaseId, ULong moduleId, ULong asccpId, ULong roleOfAccId) {
        super(AsccpReleaseManifest.ASCCP_RELEASE_MANIFEST);

        set(0, asccpReleaseManifestId);
        set(1, releaseId);
        set(2, moduleId);
        set(3, asccpId);
        set(4, roleOfAccId);
    }
}
