/*
 * This file is generated by jOOQ.
 */
package org.oagi.srt.entity.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.srt.entity.jooq.tables.BccReleaseManifest;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BccReleaseManifestRecord extends UpdatableRecordImpl<BccReleaseManifestRecord> implements Record5<ULong, ULong, ULong, ULong, ULong> {

    private static final long serialVersionUID = -1162256699;

    /**
     * Setter for <code>oagi.bcc_release_manifest.bcc_release_manifest_id</code>.
     */
    public void setBccReleaseManifestId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.bcc_release_manifest.bcc_release_manifest_id</code>.
     */
    public ULong getBccReleaseManifestId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.bcc_release_manifest.release_id</code>.
     */
    public void setReleaseId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.bcc_release_manifest.release_id</code>.
     */
    public ULong getReleaseId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.bcc_release_manifest.bcc_id</code>.
     */
    public void setBccId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.bcc_release_manifest.bcc_id</code>.
     */
    public ULong getBccId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.bcc_release_manifest.from_acc_id</code>.
     */
    public void setFromAccId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.bcc_release_manifest.from_acc_id</code>.
     */
    public ULong getFromAccId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.bcc_release_manifest.to_bccp_id</code>.
     */
    public void setToBccpId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.bcc_release_manifest.to_bccp_id</code>.
     */
    public ULong getToBccpId() {
        return (ULong) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<ULong, ULong, ULong, ULong, ULong> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<ULong, ULong, ULong, ULong, ULong> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return BccReleaseManifest.BCC_RELEASE_MANIFEST.BCC_RELEASE_MANIFEST_ID;
    }

    @Override
    public Field<ULong> field2() {
        return BccReleaseManifest.BCC_RELEASE_MANIFEST.RELEASE_ID;
    }

    @Override
    public Field<ULong> field3() {
        return BccReleaseManifest.BCC_RELEASE_MANIFEST.BCC_ID;
    }

    @Override
    public Field<ULong> field4() {
        return BccReleaseManifest.BCC_RELEASE_MANIFEST.FROM_ACC_ID;
    }

    @Override
    public Field<ULong> field5() {
        return BccReleaseManifest.BCC_RELEASE_MANIFEST.TO_BCCP_ID;
    }

    @Override
    public ULong component1() {
        return getBccReleaseManifestId();
    }

    @Override
    public ULong component2() {
        return getReleaseId();
    }

    @Override
    public ULong component3() {
        return getBccId();
    }

    @Override
    public ULong component4() {
        return getFromAccId();
    }

    @Override
    public ULong component5() {
        return getToBccpId();
    }

    @Override
    public ULong value1() {
        return getBccReleaseManifestId();
    }

    @Override
    public ULong value2() {
        return getReleaseId();
    }

    @Override
    public ULong value3() {
        return getBccId();
    }

    @Override
    public ULong value4() {
        return getFromAccId();
    }

    @Override
    public ULong value5() {
        return getToBccpId();
    }

    @Override
    public BccReleaseManifestRecord value1(ULong value) {
        setBccReleaseManifestId(value);
        return this;
    }

    @Override
    public BccReleaseManifestRecord value2(ULong value) {
        setReleaseId(value);
        return this;
    }

    @Override
    public BccReleaseManifestRecord value3(ULong value) {
        setBccId(value);
        return this;
    }

    @Override
    public BccReleaseManifestRecord value4(ULong value) {
        setFromAccId(value);
        return this;
    }

    @Override
    public BccReleaseManifestRecord value5(ULong value) {
        setToBccpId(value);
        return this;
    }

    @Override
    public BccReleaseManifestRecord values(ULong value1, ULong value2, ULong value3, ULong value4, ULong value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BccReleaseManifestRecord
     */
    public BccReleaseManifestRecord() {
        super(BccReleaseManifest.BCC_RELEASE_MANIFEST);
    }

    /**
     * Create a detached, initialised BccReleaseManifestRecord
     */
    public BccReleaseManifestRecord(ULong bccReleaseManifestId, ULong releaseId, ULong bccId, ULong fromAccId, ULong toBccpId) {
        super(BccReleaseManifest.BCC_RELEASE_MANIFEST);

        set(0, bccReleaseManifestId);
        set(1, releaseId);
        set(2, bccId);
        set(3, fromAccId);
        set(4, toBccpId);
    }
}
