/*
 * This file is generated by jOOQ.
 */
package org.oagi.srt.entity.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.srt.entity.jooq.tables.DtManifest;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtManifestRecord extends UpdatableRecordImpl<DtManifestRecord> implements Record7<ULong, ULong, ULong, ULong, ULong, ULong, ULong> {

    private static final long serialVersionUID = -1508847385;

    /**
     * Setter for <code>oagi.dt_manifest.dt_manifest_id</code>.
     */
    public void setDtManifestId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.dt_manifest.dt_manifest_id</code>.
     */
    public ULong getDtManifestId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.dt_manifest.release_id</code>.
     */
    public void setReleaseId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.dt_manifest.release_id</code>.
     */
    public ULong getReleaseId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.dt_manifest.module_id</code>.
     */
    public void setModuleId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.dt_manifest.module_id</code>.
     */
    public ULong getModuleId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.dt_manifest.dt_id</code>.
     */
    public void setDtId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.dt_manifest.dt_id</code>.
     */
    public ULong getDtId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.dt_manifest.revision_id</code>. A foreign key pointed to revision for the current record.
     */
    public void setRevisionId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.dt_manifest.revision_id</code>. A foreign key pointed to revision for the current record.
     */
    public ULong getRevisionId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>oagi.dt_manifest.prev_dt_manifest_id</code>.
     */
    public void setPrevDtManifestId(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.dt_manifest.prev_dt_manifest_id</code>.
     */
    public ULong getPrevDtManifestId() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>oagi.dt_manifest.next_dt_manifest_id</code>.
     */
    public void setNextDtManifestId(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.dt_manifest.next_dt_manifest_id</code>.
     */
    public ULong getNextDtManifestId() {
        return (ULong) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<ULong, ULong, ULong, ULong, ULong, ULong, ULong> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<ULong, ULong, ULong, ULong, ULong, ULong, ULong> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return DtManifest.DT_MANIFEST.DT_MANIFEST_ID;
    }

    @Override
    public Field<ULong> field2() {
        return DtManifest.DT_MANIFEST.RELEASE_ID;
    }

    @Override
    public Field<ULong> field3() {
        return DtManifest.DT_MANIFEST.MODULE_ID;
    }

    @Override
    public Field<ULong> field4() {
        return DtManifest.DT_MANIFEST.DT_ID;
    }

    @Override
    public Field<ULong> field5() {
        return DtManifest.DT_MANIFEST.REVISION_ID;
    }

    @Override
    public Field<ULong> field6() {
        return DtManifest.DT_MANIFEST.PREV_DT_MANIFEST_ID;
    }

    @Override
    public Field<ULong> field7() {
        return DtManifest.DT_MANIFEST.NEXT_DT_MANIFEST_ID;
    }

    @Override
    public ULong component1() {
        return getDtManifestId();
    }

    @Override
    public ULong component2() {
        return getReleaseId();
    }

    @Override
    public ULong component3() {
        return getModuleId();
    }

    @Override
    public ULong component4() {
        return getDtId();
    }

    @Override
    public ULong component5() {
        return getRevisionId();
    }

    @Override
    public ULong component6() {
        return getPrevDtManifestId();
    }

    @Override
    public ULong component7() {
        return getNextDtManifestId();
    }

    @Override
    public ULong value1() {
        return getDtManifestId();
    }

    @Override
    public ULong value2() {
        return getReleaseId();
    }

    @Override
    public ULong value3() {
        return getModuleId();
    }

    @Override
    public ULong value4() {
        return getDtId();
    }

    @Override
    public ULong value5() {
        return getRevisionId();
    }

    @Override
    public ULong value6() {
        return getPrevDtManifestId();
    }

    @Override
    public ULong value7() {
        return getNextDtManifestId();
    }

    @Override
    public DtManifestRecord value1(ULong value) {
        setDtManifestId(value);
        return this;
    }

    @Override
    public DtManifestRecord value2(ULong value) {
        setReleaseId(value);
        return this;
    }

    @Override
    public DtManifestRecord value3(ULong value) {
        setModuleId(value);
        return this;
    }

    @Override
    public DtManifestRecord value4(ULong value) {
        setDtId(value);
        return this;
    }

    @Override
    public DtManifestRecord value5(ULong value) {
        setRevisionId(value);
        return this;
    }

    @Override
    public DtManifestRecord value6(ULong value) {
        setPrevDtManifestId(value);
        return this;
    }

    @Override
    public DtManifestRecord value7(ULong value) {
        setNextDtManifestId(value);
        return this;
    }

    @Override
    public DtManifestRecord values(ULong value1, ULong value2, ULong value3, ULong value4, ULong value5, ULong value6, ULong value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DtManifestRecord
     */
    public DtManifestRecord() {
        super(DtManifest.DT_MANIFEST);
    }

    /**
     * Create a detached, initialised DtManifestRecord
     */
    public DtManifestRecord(ULong dtManifestId, ULong releaseId, ULong moduleId, ULong dtId, ULong revisionId, ULong prevDtManifestId, ULong nextDtManifestId) {
        super(DtManifest.DT_MANIFEST);

        set(0, dtManifestId);
        set(1, releaseId);
        set(2, moduleId);
        set(3, dtId);
        set(4, revisionId);
        set(5, prevDtManifestId);
        set(6, nextDtManifestId);
    }
}
