/*
 * This file is generated by jOOQ.
 */
package org.oagi.srt.entity.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.oagi.srt.entity.jooq.tables.Acc;
import org.oagi.srt.entity.jooq.tables.Ascc;
import org.oagi.srt.entity.jooq.tables.Asccp;
import org.oagi.srt.entity.jooq.tables.Bcc;
import org.oagi.srt.entity.jooq.tables.Bccp;
import org.oagi.srt.entity.jooq.tables.BizCtxAssignment;
import org.oagi.srt.entity.jooq.tables.Dt;
import org.oagi.srt.entity.jooq.tables.DtSc;
import org.oagi.srt.entity.jooq.tables.Xbt;


/**
 * A class modelling indexes of tables of the <code>oagi</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACC_ACC_GUID_IDX = Indexes0.ACC_ACC_GUID_IDX;
    public static final Index ACC_ACC_LAST_UPDATE_TIMESTAMP_DESC_IDX = Indexes0.ACC_ACC_LAST_UPDATE_TIMESTAMP_DESC_IDX;
    public static final Index ACC_ACC_REVISION_IDX = Indexes0.ACC_ACC_REVISION_IDX;
    public static final Index ASCC_ASCC_GUID_IDX = Indexes0.ASCC_ASCC_GUID_IDX;
    public static final Index ASCC_ASCC_LAST_UPDATE_TIMESTAMP_DESC_IDX = Indexes0.ASCC_ASCC_LAST_UPDATE_TIMESTAMP_DESC_IDX;
    public static final Index ASCC_ASCC_REVISION_IDX = Indexes0.ASCC_ASCC_REVISION_IDX;
    public static final Index ASCCP_ASCCP_GUID_IDX = Indexes0.ASCCP_ASCCP_GUID_IDX;
    public static final Index ASCCP_ASCCP_LAST_UPDATE_TIMESTAMP_DESC_IDX = Indexes0.ASCCP_ASCCP_LAST_UPDATE_TIMESTAMP_DESC_IDX;
    public static final Index ASCCP_ASCCP_REVISION_IDX = Indexes0.ASCCP_ASCCP_REVISION_IDX;
    public static final Index BCC_BCC_GUID_IDX = Indexes0.BCC_BCC_GUID_IDX;
    public static final Index BCC_BCC_LAST_UPDATE_TIMESTAMP_DESC_IDX = Indexes0.BCC_BCC_LAST_UPDATE_TIMESTAMP_DESC_IDX;
    public static final Index BCC_BCC_REVISION_IDX = Indexes0.BCC_BCC_REVISION_IDX;
    public static final Index BCCP_BCCP_GUID_IDX = Indexes0.BCCP_BCCP_GUID_IDX;
    public static final Index BCCP_BCCP_LAST_UPDATE_TIMESTAMP_DESC_IDX = Indexes0.BCCP_BCCP_LAST_UPDATE_TIMESTAMP_DESC_IDX;
    public static final Index BCCP_BCCP_REVISION_IDX = Indexes0.BCCP_BCCP_REVISION_IDX;
    public static final Index BIZ_CTX_ASSIGNMENT_BIZ_CTX_ID = Indexes0.BIZ_CTX_ASSIGNMENT_BIZ_CTX_ID;
    public static final Index BIZ_CTX_ASSIGNMENT_TOP_LEVEL_ABIE_ID = Indexes0.BIZ_CTX_ASSIGNMENT_TOP_LEVEL_ABIE_ID;
    public static final Index DT_DT_GUID_IDX = Indexes0.DT_DT_GUID_IDX;
    public static final Index DT_DT_LAST_UPDATE_TIMESTAMP_DESC_IDX = Indexes0.DT_DT_LAST_UPDATE_TIMESTAMP_DESC_IDX;
    public static final Index DT_DT_REVISION_IDX = Indexes0.DT_DT_REVISION_IDX;
    public static final Index DT_SC_DT_SC_GUID_IDX = Indexes0.DT_SC_DT_SC_GUID_IDX;
    public static final Index XBT_XBT_GUID_IDX = Indexes0.XBT_XBT_GUID_IDX;
    public static final Index XBT_XBT_LAST_UPDATE_TIMESTAMP_DESC_IDX = Indexes0.XBT_XBT_LAST_UPDATE_TIMESTAMP_DESC_IDX;
    public static final Index XBT_XBT_REVISION_IDX = Indexes0.XBT_XBT_REVISION_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACC_ACC_GUID_IDX = Internal.createIndex("acc_guid_idx", Acc.ACC, new OrderField[] { Acc.ACC.GUID }, false);
        public static Index ACC_ACC_LAST_UPDATE_TIMESTAMP_DESC_IDX = Internal.createIndex("acc_last_update_timestamp_desc_idx", Acc.ACC, new OrderField[] { Acc.ACC.LAST_UPDATE_TIMESTAMP }, false);
        public static Index ACC_ACC_REVISION_IDX = Internal.createIndex("acc_revision_idx", Acc.ACC, new OrderField[] { Acc.ACC.REVISION_NUM, Acc.ACC.REVISION_TRACKING_NUM }, false);
        public static Index ASCC_ASCC_GUID_IDX = Internal.createIndex("ascc_guid_idx", Ascc.ASCC, new OrderField[] { Ascc.ASCC.GUID }, false);
        public static Index ASCC_ASCC_LAST_UPDATE_TIMESTAMP_DESC_IDX = Internal.createIndex("ascc_last_update_timestamp_desc_idx", Ascc.ASCC, new OrderField[] { Ascc.ASCC.LAST_UPDATE_TIMESTAMP }, false);
        public static Index ASCC_ASCC_REVISION_IDX = Internal.createIndex("ascc_revision_idx", Ascc.ASCC, new OrderField[] { Ascc.ASCC.REVISION_NUM, Ascc.ASCC.REVISION_TRACKING_NUM }, false);
        public static Index ASCCP_ASCCP_GUID_IDX = Internal.createIndex("asccp_guid_idx", Asccp.ASCCP, new OrderField[] { Asccp.ASCCP.GUID }, false);
        public static Index ASCCP_ASCCP_LAST_UPDATE_TIMESTAMP_DESC_IDX = Internal.createIndex("asccp_last_update_timestamp_desc_idx", Asccp.ASCCP, new OrderField[] { Asccp.ASCCP.LAST_UPDATE_TIMESTAMP }, false);
        public static Index ASCCP_ASCCP_REVISION_IDX = Internal.createIndex("asccp_revision_idx", Asccp.ASCCP, new OrderField[] { Asccp.ASCCP.REVISION_NUM, Asccp.ASCCP.REVISION_TRACKING_NUM }, false);
        public static Index BCC_BCC_GUID_IDX = Internal.createIndex("bcc_guid_idx", Bcc.BCC, new OrderField[] { Bcc.BCC.GUID }, false);
        public static Index BCC_BCC_LAST_UPDATE_TIMESTAMP_DESC_IDX = Internal.createIndex("bcc_last_update_timestamp_desc_idx", Bcc.BCC, new OrderField[] { Bcc.BCC.LAST_UPDATE_TIMESTAMP }, false);
        public static Index BCC_BCC_REVISION_IDX = Internal.createIndex("bcc_revision_idx", Bcc.BCC, new OrderField[] { Bcc.BCC.REVISION_NUM, Bcc.BCC.REVISION_TRACKING_NUM }, false);
        public static Index BCCP_BCCP_GUID_IDX = Internal.createIndex("bccp_guid_idx", Bccp.BCCP, new OrderField[] { Bccp.BCCP.GUID }, false);
        public static Index BCCP_BCCP_LAST_UPDATE_TIMESTAMP_DESC_IDX = Internal.createIndex("bccp_last_update_timestamp_desc_idx", Bccp.BCCP, new OrderField[] { Bccp.BCCP.LAST_UPDATE_TIMESTAMP }, false);
        public static Index BCCP_BCCP_REVISION_IDX = Internal.createIndex("bccp_revision_idx", Bccp.BCCP, new OrderField[] { Bccp.BCCP.REVISION_NUM, Bccp.BCCP.REVISION_TRACKING_NUM }, false);
        public static Index BIZ_CTX_ASSIGNMENT_BIZ_CTX_ID = Internal.createIndex("biz_ctx_id", BizCtxAssignment.BIZ_CTX_ASSIGNMENT, new OrderField[] { BizCtxAssignment.BIZ_CTX_ASSIGNMENT.BIZ_CTX_ID }, false);
        public static Index BIZ_CTX_ASSIGNMENT_TOP_LEVEL_ABIE_ID = Internal.createIndex("top_level_abie_id", BizCtxAssignment.BIZ_CTX_ASSIGNMENT, new OrderField[] { BizCtxAssignment.BIZ_CTX_ASSIGNMENT.TOP_LEVEL_ABIE_ID }, false);
        public static Index DT_DT_GUID_IDX = Internal.createIndex("dt_guid_idx", Dt.DT, new OrderField[] { Dt.DT.GUID }, false);
        public static Index DT_DT_LAST_UPDATE_TIMESTAMP_DESC_IDX = Internal.createIndex("dt_last_update_timestamp_desc_idx", Dt.DT, new OrderField[] { Dt.DT.LAST_UPDATE_TIMESTAMP }, false);
        public static Index DT_DT_REVISION_IDX = Internal.createIndex("dt_revision_idx", Dt.DT, new OrderField[] { Dt.DT.REVISION_NUM, Dt.DT.REVISION_TRACKING_NUM }, false);
        public static Index DT_SC_DT_SC_GUID_IDX = Internal.createIndex("dt_sc_guid_idx", DtSc.DT_SC, new OrderField[] { DtSc.DT_SC.GUID }, false);
        public static Index XBT_XBT_GUID_IDX = Internal.createIndex("xbt_guid_idx", Xbt.XBT, new OrderField[] { Xbt.XBT.GUID }, false);
        public static Index XBT_XBT_LAST_UPDATE_TIMESTAMP_DESC_IDX = Internal.createIndex("xbt_last_update_timestamp_desc_idx", Xbt.XBT, new OrderField[] { Xbt.XBT.LAST_UPDATE_TIMESTAMP }, false);
        public static Index XBT_XBT_REVISION_IDX = Internal.createIndex("xbt_revision_idx", Xbt.XBT, new OrderField[] { Xbt.XBT.REVISION_NUM, Xbt.XBT.REVISION_TRACKING_NUM }, false);
    }
}
